### ISSUE TITLE
Typo in cardanoroadmap.com

### ISSUE THREAD

**Issue by davelab6** [input-output-hk/cardanodocs.com#69]
https://cardanoroadmap.com/ has,

> from the field programming language theory

This should be,

> from the field of programming language theory

I couldn't find that page in this orgs repos to make a pr directly; I wonder if all the cardano websites have GitHub repos?

**Comment by denisshevchenko** [comment]
Thanks, @davelab6! It will be fixed.

**Comment by davelab6** [comment]
Please leave the issue open until it is actually fixed

**Comment by denisshevchenko** [comment]
Now it's fixed. Sorry for delay.

**Comment by davelab6** [comment]
Thank you Denis!! 

Will all the cardano websites have GitHub repos?

**Comment by denisshevchenko** [comment]
No, not all. But in some future (I hope) they all will have a GitHub repos.

**Comment by gufmar** [comment]
sorry when I place a note here. wouldn't create a new issue before it's clear if and how this will be organized in the (near) future.
I and other forum and chat members had announced multiple times some (little) errors on all the different websites. But it looks like (and I fully understand) that during last days a limited staff had to do many other and more important things. 
One of this signalisation was on cardanohubs homepage the central (404 dead) link to Ouroboros.
As we are not all mathematicians, crypto-experts or haskell-coders we may help you with little tasks on your websites. For example some German and Italian translations.

BTW: Not sure if there was a certain special reason to set up so much different domains. Maybe because you wouldn't appear like one big centralised company. But this current situation favourites usage of cardano-Domains by third (bad) parties. New entering people can hardly understand whats trustworthy and scamming sites. I would recommend moving all to subdomains of one official main domain. (just my 2 cents)

**Comment by davelab6** [comment]
I agree with @gufmar - there are a lot of small errors in (what I believe are) official Cardano Project pages, and now that Cardano is in the spotlight with its high market cap, I propose that placing all the official site sources on Github will be the best way to resolve those errors.

**Comment by denisshevchenko** [comment]
Thanks, @gufmar, I'll ask about this idea.
