### ISSUE TITLE
add Support the Brazilian Portuguese.

### ISSUE THREAD

**Issue by EvertonMelo** [input-output-hk/cardanodocs.com#95]
#94

**Comment by gufmar** [comment]
Hi @EvertonMelo 
great if you wanna start the create and support the Brazilian/Portuguese version.
As I started to work on a German version please have also a look at this thread https://github.com/input-output-hk/cardanodocs.com/issues/75
As you can see the suggestion was to fork instead of creating a branch inside the IOHK repositories. But in my opinion, it would make more sense doing it as pull requests in the master branch, (of course only after all - or most - page translations are ready)

I'm sure you already know: 
Your next step would be to adapt 3 files in _includes folder as I did here https://github.com/gufmar/cardanodocs.com/tree/master/_includes
And the current CI requires a flag in png format having a transparent background with rounded corners like I prepared at https://github.com/gufmar/cardanodocs.com/tree/master/img 
For the page translations, you have to create the /pt subfolder in _docs 

@tomasvrana what's your thoughts on this?

**Comment by marcusoregano** [comment]
Good @EvertonMelo !
Hope we can help you with that.
I'm a native speaker of PT_BR

**Comment by EvertonMelo** [comment]
@gufmar What's the best way to do this? 
I have already verified that in both Chinese and German, we can use the structure. 
Could you create the structure of the files in Pt the pt-br?

**Comment by gufmar** [comment]
I just cleaned up to root folder (there was copies of _doc, _includes, _layouts and _pages (all without initial underscore) This was an attempt to get the github-pages working. I don't know thy the original IOHL repo uses this folders with initial _.
I also created _docs/pt with a copy of the original English documents. Feel free to start working on therein

**Comment by EvertonMelo** [comment]
Thank you.

**Comment by EvertonMelo** [comment]
the pullrequest start on: 
https://github.com/CardanodocTranslations/cardanodocs.translations/tree/master/_docs/pt
